spring.application.name=Cloud-Config-Server
server.port=8888
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=classpath:/config-repo
management.endpoints.web.exposure.exclude=env,configprops
management.endpoint.env.access=none
management.endpoint.env.roles=ADMIN
management.endpoint.env.show-values=never
management.endpoints.web.exposure.include=env